plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sami.voice'
    compileSdk 33
    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.sami.voice'
        minSdk 23
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }
}
